# Generated by Django 5.2.1 on 2025-05-15 09:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_point_player_points_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.RemoveField(
            model_name='ship',
            name='player',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='game',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='target',
        ),
        migrations.AddField(
            model_name='shot',
            name='board',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='main.board'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='main.game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], default=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Finished'), (2, 'In Progress')]),
        ),
        migrations.AlterField(
            model_name='ship',
            name='size',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
