# Generated by Django 5.1.1 on 2025-05-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_game_creator_alter_game_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard'), (3, 'Dummy')]),
        ),
    ]
